version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_golang
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge